### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by wuchangfeng** [Gracker/Girls#1]
你好 fork 了一下您的项目。发现 BottomBar 在 item 为 3 个时，item 的 title 是默认显示的。在 item 大于 3 时，title 只有点击 item 之后再显示。目前我还没找到为什么，还想请问你知不知道原因？

谢谢啦。

**Comment by Gracker** [comment]
是这样的,BottomBar的规范里面说:当 item 小于或者等于3个的时候,就会默认显示 title , 大于3个就会点击之后才会显示. BottomBar 的作者遵循了这个规范.

你可以在代码中加入下面一句话,来强制显示所有 item 的title:
`// Show all titles even when there's more than three tabs.
mBottomBar.useFixedMode();`

**Comment by wuchangfeng** [comment]
@Gracker 谢谢。原来这样啊，我得去看看 BottomBar 的设计规范了。另外 mBottomBar.useFixedMode() 当设置这个属性时候，BottomBar 背景颜色会自动变成白色，点击时候 icon 和 title 会变成淡绿色。这也是默认的吗？

**Comment by Gracker** [comment]
是默认的，可以修改。
具体你可以看看 BottomBar 那个项目的 Readme

**Comment by wuchangfeng** [comment]
好，谢谢啊。
